includes/class-wc-gateway-stripe.php
The value of `$souce->source` is a string not an object.
Fixes #2.
=> Fixed notice trying to get property of non-object.

includes/class-wc-stripe-customer.php
Fixes #5.
- Uses `$responses` instead of `$result` which is undefined
=> Fixed notice of undefined $result.

woocommerce-gateway-stripe.php
Fixes #3.
- Add admin notice globally when secret key is empty. This acts as CTA for merchant when choosing Stripe via on-boarding wizard.
=> Prompt, via admin notice, to set API keys if not set.

includes/class-wc-stripe-customer.php
This fixes missing first arg error.
Fixes #15.
=> Make first arg has default value empty array.

woocommerce-gateway-stripe.php
Fixes #20.
- Add extra `OR` check (if pre-orders is enabled) when loading add-ons class.
=> Make sure addons is laoded when pre-orders is enabled.

includes/class-wc-gateway-stripe.php
Fixes #18.
- Add order note when charge is complete
=> Added missing order note when charge is complete.

includes/class-wc-gateway-stripe.php, woocommerce-gateway-stripe.php
Fixes #19 .
- Add a missing method to a class. This method is referenced in a filter but can't be reached so the filter returns a null value resulting in a blank payment methods page.
=> Fix payment methods not showing up

woocommerce-gateway-stripe.php
Fixes #28 
- This patch removes the error notice when trying to enabling Stipe plugin when WooCommerce is **not** activated.
=> Notice Message Upon Activation if WC not Active Fix

includes/class-wc-gateway-stripe-addons.php, includes/class-wc-gateway-stripe.php
Fixes #37
This patch removes the renewal payment retry system introduced with SHA: fb1cdf410 which would delete the card and potentially the customer tokens from a renewal order and use the tokens on the customer's account instead. This lead to issues outlined in #37.
It also sneaks in a typo fix with SHA: 90ff54830
=> Remove renewal payment retry

includes/class-wc-gateway-stripe.php, readme.txt
Fixes #72 
cc @dwainm for review.
Fix - When adding declined cards, fatal error is thrown.
=> Fix when adding declined cards, fatal error is thrown fixes #72

includes/class-wc-gateway-stripe.php, readme.txt
Fixes #99
cc @gedex for review.
* Fix - Bitcoin image not showing.
=> Fix bitcoin image not showing closes #99

includes/class-wc-gateway-stripe.php, readme.txt
Fixes #115 
cc @gedex for review.
* Fix - Paying for order incorrectly uses cart amount.
=> Paying for order incorrectly uses cart amount closes #115

includes/class-wc-stripe-apple-pay.php
Looks like a copy-paste error, because `administrativeArea` is State and `locality` is City
=> Set shipping `locality` to City

includes/class-wc-gateway-stripe-addons.php
Fixes https://github.com/woocommerce/woocommerce-gateway-stripe/issues/124
This was causing double stock reduction in preorders. Tested with both Upon Release and Charge Up Front orders.
@roykho
=> Preorders: Prevent double stock reduction

readme.txt
The first line of the Changelog under 3.1.0 reads
* New - **Apply** Pay Support
I've corrected it to read 
* New - **Apple** Pay Support.
Bold emphasis above is mine.
=> Corrected readme.txt to read Apple Pay Support

readme.txt
Addresses #147.
Adjusts the copy of the readme file to include mentions of Apple Pay and Web Payments API.
@MarinaWoo - how does this copy look to you?
cc @roykho for merge before we deploy. I haven't adjusted the version number in the readme file.
=> Adjusts the readme file to include mention of Apple Pay and Web Payments API

includes/class-wc-gateway-stripe-addons.php, readme.txt
Fixes #149 
* Fix - Retry failed subscription payments with customer ID.
Retries can fail if customer has changed/removed their associated credit card on file. This fix will try to process their payment via their customer ID instead if that happens. Don't mind the DRY for now as there are several places that needs to be refactored when I get more time.
=> Retry failed subs payments with customer id closes #149

includes/class-wc-gateway-stripe-addons.php
Fixes #239
Fix more notices for WC 30 on addons. 
@gedex did you also get this notice when testing `PHP Notice:  Undefined variable: item_array in /srv/www/gitwooplugins/wp-content/plugins/woocommerce/includes/wc-order-item-functions.php on line 32`
I am not sure where that is coming from.
=> Fix more WC 30 notices closes #239

includes/class-wc-gateway-stripe.php
As discussed with @roykho, this PR adds two new filters:
- `wc_stripe_display_save_payment_method_checkbox` is used to control whether or not to display the checkbox to let users save their credit card.
- `wc_stripe_force_customer_creation` is used to allow sites to always save credit cards without first asking the user.
With those two filters, sites will be able to save customers credit cards without asking.
=> Add two filters to control whether or not to save cards and to display the save payment method checkbox

includes/legacy/class-wc-gateway-stripe.php
Fixes # Cannot use stripe-checkout for legacy version WC2.5 .
- Fixed a broken link to renamed stripe-checkout.js
=> Fix of broken link to stripe-checkout.js

includes/class-wc-gateway-stripe-addons.php, readme.txt
Fixes #247
* Fix - Handle a subscription renewal failed payment order correctly to prevent orders going into onhold status.
When a subs order is renewed, sometimes payment fails. When this happens the order is not handled properly and it first goes into on-hold status and then fail. But doing this, causes order email to be sent to customers again causing confusion.
This patch properly handles the error and prevents the order going into on-hold. Instead it will just fail.
=> Handle subs renewal failed payment closes #247

includes/class-wc-gateway-stripe.php, includes/legacy/class-wc-gateway-stripe.php, includes/settings-stripe.php, woocommerce-gateway-stripe.php
For clarity purpose this PR adds some useful links to specific elements of the Stripe settings page:
- Add link on SSL certificates
https://en.wikipedia.org/wiki/Transport_Layer_Security
- Add link to Apple Pay https://woocommerce.com/apple-pay/
- Add link Stripe sign-up page https://dashboard.stripe.com/register
- Add link to Stripe API keys page
https://dashboard.stripe.com/account/apikeys
- Add link to ISO codes
http://www.w3schools.com/tags/ref_language_codes.asp
=> Add useful links to the Stripe settings page

includes/class-wc-stripe-api.php, woocommerce-gateway-stripe.php
- Changes to User-Agent header to be more similar with the Stripe bindings[0] which will allow for better tracking.
[0] https://github.com/stripe/stripe-php/blob/master/lib/ApiRequestor.php#L174-L203
=> [4.0] User Agent changes for better tracking

includes/admin/stripe-p24-settings.php, includes/class-wc-gateway-stripe.php, includes/payment-methods/class-wc-gateway-stripe-p24.php, woocommerce-gateway-stripe.php
@roykho I wanted to get a feeling for how easy it is to add a new payment method with the example of adding P24 which is very similar to iDEAL in its flow: https://stripe.com/docs/sources/p24
However, I think I'm missing a couple of things, and I would highly appreciate if you could review and assess what I'm missing. From what I can see I'm missing the following bits:
* no P24 logo in payment font (any idea if that's easy to add?)
* "Refund via Stripe P24" is disabled (couldn't find how to enable it)
* Order in the wc-settings (for some reason it's listed before Stripe in the "Checkout options" breadcrumb menu, no idea why)
* missing mentions in `languages/woocommerce-gateway-stripe.pot` file (do I just add any references to lines that "print" some text?)
Am I missing anything else?
But …
=> add payment method Stripe Przelewy24 (P24)

readme.txt
Based on this question in the forum - https://wordpress.org/support/topic/does-woocommerce-stripe-payment-gateway-require-an-ssl-certificate/ it isn't clear that an SSL certificate is required.
-
=> Update FAQ to reflect the need for an SSL Certificate

includes/abstracts/abstract-wc-stripe-payment-gateway.php
hello, this pull request correct the problem regarding a partial refund. The updated Stripe fee is not correct. This corrects him.
=> Fix `update_fees()`, the calculation is wrong (refund)

includes/abstracts/abstract-wc-stripe-payment-gateway.php, includes/class-wc-stripe-webhook-handler.php, includes/payment-methods/class-wc-stripe-payment-request.php, readme.txt
Fixes #261
* Add - Webhooks for review open/closed for Radar.
=> Add webhooks for review open/closed Radar closes #261

includes/abstracts/abstract-wc-stripe-payment-gateway.php
Save the currency during the transaction with Stripe.
Thus the PR #527  can display a coherent value.
=> Fix / save the Stripe currency during the transaction

includes/admin/stripe-multibanco-settings.php, includes/payment-methods/class-wc-gateway-stripe-multibanco.php, woocommerce-gateway-stripe.php
- adds the receiver flow payment method Multibanco: https://stripe.com/docs/sources/multibanco
- receiver flow information is shown in a redirect / Multibanco hosted page
- Receiver information is added to the on-hold email
- Order is put on hold while we're waiting to receive the funds
@roykho I've reused the way of setting the statement descriptor based on `$main_settings['statement_descriptor']` however, if that's empty an empty string value is provided which will make source creation error. This affects all source creations. Should I open in a separate issue?
=> add multibanco payment method

includes/class-wc-stripe-helper.php
On a big woocommerce installation (21.7 million postmetas) we were seeing timeouts on webhook because these queries were taking more than 40 seconds 
Fixes # .
- add meta keys in WHERE clauses
=> Avoid full table scan while getting orders from source id or charge id

includes/class-wc-stripe-api.php
Fixes #652
- adds the api and request sent to Stripe that failed
=> Add the api and request to the log about the failure

changelog.txt, includes/class-wc-gateway-stripe.php
Fixes #647
* Tweak - Make 3DS object is in pending status before redirecting.
=> Make sure 3DS object is in pending status before redirecting closes #647

assets/css/stripe-storefront-styles.css, assets/css/stripe-styles.css, assets/css/stripe-twentyseventeen-styles.css, includes/class-wc-gateway-stripe.php, languages/woocommerce-gateway-stripe.pot
Fixes #661
Here is one method to get it working is conditional load styles depending on whether the radio button has special styling. So in this case I am just conditionally checking if the themes are Storefront or TwentySeventeen.
Things to check. Make sure alignment is correct on Checkout page AND on Add Payment Method page. Test Storefront, TwentySeventeen and other themes that does NOT have special styling to the radio buttons.
=> Adjust styles

changelog.txt, includes/abstracts/abstract-wc-stripe-payment-gateway.php, includes/class-wc-stripe-webhook-handler.php
Fixes #671
* Fix - Asynchronous payment methods such as SEPA, did not show order Stripe fees/net after payment succeed.
=> Fix order not showing stripe fees for asynchronous payments closes #671

includes/class-wc-stripe-logger.php
This updates the stripe logger's internal log instance creation.
The change makes use of the shared `WC_Logger` instance instead of how it currently is: a new WC_Logger instance is created specifically for stripe.
We need to add this to allow for the class to be filtered out and replaced by a custom class, in our case WooCommerce.com, but this will help all other large scale sites.
The default from `wc_get_logger` is simply an instance of WC_Logger, but anyone can replace this.
For more detail see:
https://alphamattic.wordpress.com/2018/06/01/double-charging-customers/#comment-4994
https://a8c.slack.com/archives/C4E0DVDB2/p1528186755000071
=> Make the stripe logger overridable.

changelog.txt, includes/class-wc-stripe-customer.php, includes/class-wc-stripe-order-handler.php, includes/class-wc-stripe-webhook-handler.php, languages/woocommerce-gateway-stripe.pot
Fixes #683 #684
* Fix - 3DS payment sometimes will create additional transaction in Stripe.
=> Fix 3DS sometimes causes second payment retry closes #683 #684

includes/class-wc-stripe-apple-pay-registration.php
The admin notice is show to everybody but only user with special roles can make the change needed. Shop managers can't, for example. So display the notice only to users capable of 'manage_woocommerce'.
Fixes # .
-
=> Only show apple pay  admin notice to user who can change options

changelog.txt, includes/class-wc-gateway-stripe.php
Fixes #703
* Fix - Fatal error when clicking on order link that doesn't exist.
=> Fix error on order link when it no longer exists closes #703

changelog.txt, includes/compat/class-wc-stripe-subs-compat.php
Fixes #711
* Fix - Undefined property error on card type in rare cases.
=> Fix undefined property error on card type in rare cases closes #711

changelog.txt, includes/class-wc-gateway-stripe.php
Fixes #706
* Fix - When 3DS card redirect status is "not_required", charge the 3DS source.
=> Use 3DS source when redirect status is not required closes #706

changelog.txt, includes/class-wc-gateway-stripe.php
Found while testing.
* Fix - Test mode info not showing when description field is left blank.
=> Show test mode info even if description field is empty

includes/compat/class-wc-stripe-subs-compat.php
Fixes #732.
- Delete legacy `_stripe_card_id` when saving the credit card token in the new `_stripe_source_id` meta,
- Cleanup ternary operators in the `add_subscription_payment_meta` function.
=> Delete legacy card token from subscription meta when saving the new one

includes/admin/class-wc-stripe-admin-notices.php
Before: 
Link to image here: http://cld.wthms.co/8GH30E.
After:
Link to image here: http://cld.wthms.co/j5bJZt.
- A bit of an update of the CSS
=> Fixes text of notice behind dismiss element

assets/js/stripe.js, includes/abstracts/abstract-wc-stripe-payment-gateway.php, includes/class-wc-gateway-stripe.php
This PR includes a minimal set of changes in order to start supporting Stripe PaymentIntents (currently) in parallel to source objects.
To minimize the proof-of-concept changes required, I did not strip the support for "old-school" sources within `WC_Gateway_Stripe`. Instead, I am using a slightly modified flow in order to extract a source object from payment intents and proceed as usual.
Some of the needed follow-up PRs:
1. Replace all `ToDo` keywords/comments with the proper functionality.
2. Stop accessing sources directly within `WC_Gateway_Stripe` in favor of a PaymentIntent-first approach.
3. Consider eliminating the Stripe Checkout modal and/or check how it works with PaymentIntents.
Create a new order and use one of the *3D Secure test card numbers and tokens* from …
=> Adding basic PaymentIntent support for first-time buyers

assets/js/stripe.js, includes/class-wc-gateway-stripe.php, includes/class-wc-stripe-intent-generator.php, woocommerce-gateway-stripe.php
Fixes #787.
This PR introduces the `WC_Stripe_Intent_Generator`, which uses the new `get_intent_and_secret` method of `WC_Gateway_Stripe` in order to only generate payment intents when the checkout form is being submitted.
With this change, payment intents will not be generated on every visit of the checkout page. This way merchants will not see empty payment intents in their dashboards and the checkout page loads faster.
To prevent unintended direct access to the new AJAX endpoint, `WC_Stripe_Intent_Generator` will check if the cart has contents, and only create a payment intent when the cart is not empty. This is why a standard WC_AJAX action is used, instead of a REST API endpoint.
Try creating an order with a credit card. The process should start with a local AJAX request before …
=> SCA: Create the PaymentIntent just when the checkout form is submitted 

includes/abstracts/abstract-wc-stripe-payment-gateway.php, includes/class-wc-gateway-stripe.php
Fixes #784.
- Extracted parts of `process_payment` to separate methods to improve readability.
- Although the initial purpose of this PR was to only use intents within `WC_Gateway_Stripe` and ditch sources, it turned out that this would not work with Stripe Checkout.
- There is a clear separation between intents and sources in terms of loading and processing.
__Note:__ This is a stacked PR that needs to be merged into https://github.com/woocommerce/woocommerce-gateway-stripe/pull/795. Focus on that one first, please.
=> SCA: Use both intents and sources within `process_payment`

assets/js/stripe-admin.js, includes/abstracts/abstract-wc-stripe-payment-gateway.php, includes/admin/stripe-settings.php, includes/class-wc-gateway-stripe.php, tests/phpunit/test-wc-stripe.php
Fixes #788.
Cleanup of 3D Secure-related code, as PaymentIntents will handle authentication within an overlay on the checkout page.
=>  SCA: Remove the old "three_d_secure" logic

assets/js/stripe.js
I started this PR a while back in order to fully understand the checkout flow in `stripe.js` and what needs to be changed. During the process I did:
1. Add JSDoc comments to every method to clarify what it does both to myself and the next developer that works on the extension.
2. Removed the parts, related to Stripe Checkout (as I thought it's becoming obsolete and will be removed), then restored them, along with comments.
3. *Most importantly,* I realized that most "personalities" (separate payment options like Sofort and etc.) do not involve any JavaScript actions and use follow-up redirects instead. 
Most of the changes in those two methods are related to the fact that if either of the following methods returns `true`, the form handler with detach itself and re-submit the form:
- …
=> SCA: JavaScript inline docs & cleanup

includes/class-wc-gateway-stripe.php
Fixes #797 .
- Add basic `description` and `statement_descriptor` while creating payment intents.
- Update the `description` field of the payment intent and add the necessary `metadata` to it before capturing the payment.
This is a part of the PR:
```php
$full_request = $this->generate_payment_request( $order, $prepared_source );
$updated_data = array(
'description' => $full_request['description'],
'metadata'    => $full_request['metadata'],
);
```
In order to avoid duplicate code and allow existing filters to work, I am calling `generate_payment_request` even though I am only partially using the data that it generates. Do you consider this an issue?
=> SCA: Add order meta

includes/class-wc-gateway-stripe.php
Fixes #789 
After calling `/payment_intents/xxxxx/capture`, the returned response is guaranteed to have at least 1 `Charge` object in its list. But, it's possible for a Payment intent to have multiple charges, for example for partial payments or if there have been retries on the same Intent object. It's safer to return the last Charge object instead of the first.
=> Always return the last charge made to a PaymentIntent, instead of the first one

includes/admin/class-wc-stripe-privacy.php, package.json, readme.txt
Explicitly place the "Retain Stripe Data" setting at the end of the `personal_data_retention` section of settings instead of appending it as the second to last entry in the settings array. 
1. WooCommerce > Settings > Accounts & Privacy
2. The "Retain Stripe Data" should be the last entry in the "Personal data retention" section.
=> Setting: Retain Stripe Data, place in correct spot settings array

woocommerce-gateway-stripe.php
Reverts woocommerce/woocommerce-gateway-stripe#842
This is not a recommended version change. Version 5.1 instead of 5.1.1 should be used.
=> Revert "Update woocommerce-gateway-stripe.php"

includes/class-wc-gateway-stripe.php, includes/class-wc-stripe-api.php
The Stripe API version has been bumped to `2019-02-19` in `master` here: https://github.com/woocommerce/woocommerce-gateway-stripe/commit/7b32ad1710f6693d73fc8f4c1bdb064a8420a0fa
This PR makes the same change for the SCA feature branch. There were some minor naming changes related to Payment Intents, described here: https://stripe.com/docs/upgrades#2019-02-11
=> Update the Stripe's API version we support

includes/class-wc-gateway-stripe.php
The "return" statement was removed here: https://github.com/woocommerce/woocommerce-gateway-stripe/commit/b2a9812b40c412bdc41297315e65bff526e8acd1#diff-2f62df4143b223ac0f7805c02376412eL456
It looks like its removal was unintended.
=> Bail if the site is HTTP and testing mode is disabled

changelog.txt, includes/abstracts/abstract-wc-stripe-payment-gateway.php, includes/admin/class-wc-stripe-admin-notices.php, package.json, readme.txt, woocommerce-gateway-stripe.php
Fixes #835 (see the issue for more context)
The notice is a `warning`, non-dismissable, and it only appears if the `Stripe Modal Checkout` option is checked. The notice has a link to this page, which will have relevant info by Monday: https://docs.woocommerce.com/document/stripe/modal-checkout
I also took the liberty of getting the plugin ready to cut the `4.1.16` release on Monday.
=> Add warning notice for merchants that use the Modal checkout

changelog.txt, includes/payment-methods/class-wc-stripe-payment-request.php
Fixes #844 .
- Add Puerto Rico to allowable countries list.
Test:
* Set store's base location to Puerto Rico.
* Enable Payment Request Buttons if not already enabled.
* Visit a product page and note how Stripe Payment Request JS files are not included.
* Checkout this branch and make sure Apple Pay & Google Pay buttons available.
=> PR: Payment Request Buttons: Add Puerto Rico to allowable countries list

includes/abstracts/abstract-wc-stripe-payment-gateway.php, includes/class-wc-stripe-webhook-handler.php
Fixes https://github.com/woocommerce/woocommerce-gateway-stripe/issues/851
Stripe treats a "partial capture" (capturing a payment for less money that was originally authorized) as a `Charge` object with a partial `Refund` inside it.
When doing a partial capture from the Stripe Dashboard, we rely on the `charge.captured` Webhook to update the order and the Stripe fees. Before, everything worked, except that the fees were being calculated wrong (the resulting fees would be for the whole payment, whereas the correct fees should be `full_payment_fees - partial_refund_fees`). This PR fixes that.
@dechov I haven't been able to fully reproduce the original issue. Apart from the wrong calculation of the fees, everything else seemed to be working fine. This is a screenshor of a `$20.95` order with …
=> Correctly calculate Stripe fees when doing a partial capture through Stripe Dashboard

includes/abstracts/abstract-wc-stripe-payment-gateway.php, includes/class-wc-gateway-stripe.php
This PR ensures that the gateway works correctly back to WooCommerce 2.6. The amount of needed changes is surprisingly small based on the fact that we have 1000+ additions in `sca/master`.
Checkout WooCommerce 2.6 and do a couple of tests with the gateway:
- With a standard (non-3DS card)
- With a 3DS card
- With webhooks enabled (and check the response of webhooks in Stripe Dashboard)
=> SCA: Add compatibility back to WooCommerce 2.6

assets/js/stripe.js
When handling errors, the extension selects all `.stripe-source-errors` elements and fills them with the error message, which might cause a state like this:
__Broken state:__
In this PR I'm selecting the correct element:
- Just `.stripe-source-errors` if there are no saved cards.
- The element within the current saved card `li` if one is chosen.
- The element within `#wc-stripe-cc-form` for freshly entered cards.
__Saved card:__
__New card:__
1. Add multiple saved cards
2. Force an error (ex. failed SCA auth)
3. Ensure that no matter what is chosen, only one message appears and it appears in the right place.
=> SCA/FIX: Prevent multiple error messages because of saved cards

includes/admin/class-wc-stripe-admin-notices.php, includes/class-wc-gateway-stripe.php
Reverts 3D secure notice (which appeared to cause some anomalous behavior: p1559144950004400-slack-woo-par-hydra-reserve) added in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/795 (https://github.com/woocommerce/woocommerce-gateway-stripe/pull/795/commits/fd458bc7f757de9daf689d03b2ce942c8e0d91c4), in favor of equivalent notice in the `WC_Stripe_Admin_Notices` class.
Also removes Stripe Checkout warning added in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/837, since Stripe Checkout was removed in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/846.
=> Move 3D Secure notice to notices class, replacing Stripe Checkout notice

assets/js/stripe.js, includes/class-wc-gateway-stripe.php, includes/payment-methods/class-wc-stripe-payment-request.php
Fixes #877
Makes sure payment intent authorization handling (in assets/js/stripe.js) is enqueued whenever Payment Request Button is present, to prevent stalling and allow completion of payment.
=> Enqueue woocommerce_stripe script alongside wc_stripe_payment_request script

includes/class-wc-stripe-order-handler.php
See https://github.com/woocommerce/woocommerce/issues/23626 and https://github.com/woocommerce/woocommerce/pull/23634 for context.
=> Make the capture / cancel-auth processes work even if the order is in a custom status

changelog.txt, includes/class-wc-gateway-stripe.php, readme.txt
Fixes https://github.com/woocommerce/woocommerce-gateway-stripe/issues/882
The verify_intent nonce is created after the processing of the customer, in the same `process_checkout` handler but the session token (a component of the nonce) isn't accessible in `$_COOKIE` until the next page load. Therefore the nonce is obsolete as soon as the response comes back.
This change is to ensure that the newly created and logged in customer is the one reflected in the current session. Is there any reason to not be writing to $_COOKIE directly?
Tested using steps in https://github.com/woocommerce/woocommerce-gateway-stripe/issues/882.
See https://github.com/woocommerce/woocommerce-gateway-stripe/pull/886 for an alternative solution. Kudos to @RadoslavGeorgiev for setting me on the right (after being on …
=> Proceed with current request using new login session to ensure consistent nonce

includes/admin/class-wc-stripe-admin-notices.php
Fixes #881 .
As @dechov suggested in #881, replaced `https://stripe.com/docs/payments/dynamic-3ds` with `https://stripe.com/docs/payments/3d-secure#three-ds-radar` in the 3DS notice.
It's a simple link change, so no real tests are needed. If you still need to see the notice:
1. Install a pre-`4.2.0` version of Stripe.
2. Enable 3DS in the gateway's settings.
3. Check out the branch of this PR.
4. See the notice.
=> Updating the link in the 3DS notice.

changelog.txt, includes/abstracts/abstract-wc-stripe-payment-gateway.php, includes/class-wc-gateway-stripe.php, includes/class-wc-stripe-order-handler.php, includes/class-wc-stripe-webhook-handler.php, readme.txt
Fixes #889
`WC_Gateway_Stripe::verify_intent_after_checkout` (called during the redirect from Checkout to Thank You) contains something like this:
```php
if ( 'pending' !== $order->get_status() && 'failed' !== $order->get_status() ) {
// If payment has already been completed, this function is redundant.
return;
}
$intent = $this->get_intent_from_order( $order ); // A slow function, because of remote calls
if ( $this->lock_order_payment( $order, $intent ) ) {
// Do not proceed if the order is being handled by a webhook at the moment.
return;
}
```
The locking mechanism works fine __if__ this method gets entered __while__ a webhook is handling the intent confirmation. However, if the webhook is much faster, or retrieving the intent in this method takes a while, it does not. The reason for …
=> Fix duplicate intent actions when webhooks are enabled.

changelog.txt, includes/class-wc-stripe-order-handler.php, readme.txt, woocommerce-gateway-stripe.php
Fixes https://github.com/woocommerce/woocommerce-gateway-stripe/issues/900
Old-old behaviour (pre-4.2):
- Moving an order `On-Hold -> Cancelled` would refund/void the payment.
- Moving an order `On-Hold -> Refunded` would refund/void the payment.
That didn't work well if the merchant uses custom order statuses. So...
Current behaviour:
- Moving an order `* -> Cancelled` would refund/void the payment.
- Moving an order `* -> Refunded` would refund/void the payment.
That's worse, because it means that cancelling an order, even if the order was already fulfilled, would refund the payment. That's specially bad with Subscriptions, because a "Cancelled" subscription just means "don't renew it anymore", it shouldn't refund any existing payment.
Proposed behaviour:
- Moving an order `* -> …
=>  Fix - Changing an order status to "Cancelled" will no longer refund the payment.

changelog.txt, includes/class-wc-stripe-webhook-handler.php, readme.txt
Fixed #902
Detailed to reproduce are in #902. Basically:
- Payment gets declined
- User tries another card, payment succeeds
- Somehow the first "payment failed" webhook is sent afterwards
With this change, the delayed webhook will be ignored because the order is not on a `pending` or `failed` status, so the order will stay in `processing` status.
=> Don't process any delayed payment failure if the order has already transitioned status

changelog.txt, includes/class-wc-gateway-stripe.php, readme.txt
Fixes #913
- The payment intent comes back marked as `requires_capture` so we can still process it and the merchant will need to capture it manually
* Follow the repro steps in #913 
* The customer should be shown a success message
* The order should be marked as on hold
* Manually processing the order should successfully capture the transaction
=> Fix successful retries of 3ds failing

changelog.txt, includes/admin/stripe-settings.php, readme.txt
Fixes #895
The test/live publishable keys aren't "secrets", they are injected into the DOM on the checkout in plain text. There's no need for those fields to be `type=password`, it just makes it more annoying to setup.
To test: Go to the Stripe payment method settings, see that the `Test Publishable Key` / `Live Publishable Key` input fields are displayed in plain text.
=> Make the publishable key fields be plain text instead of "password"

changelog.txt, includes/class-wc-stripe-webhook-handler.php, readme.txt
Fixes #818
Sorry this issue flew under our radar (pun absolutely intended) for so long.
When a payment triggers a Stripe Radar rule and it's placed "under review", the merchant's site is notified woth a webhook. When the merchant goes to Stripe Dashboard and approves the review ("unlocking" the payment), there's another webhook.
The webhooks `review.opened` and `review.closed` previously had a property `object.charge` with the Charge ID that triggered the review. Now, with the Payment Intent logic, that property is `null`, and instead the webhook includes the Intent ID in `object.payment_intent`. This PR fixes the webhook logic to look for the `payment_intent` property.
To test:
- Make a payment using this CC: `4000000000009235`
- On the order screen, you'll see that it has been pun "On …
=> Fix the Radar-related webhooks

includes/class-wc-stripe-webhook-handler.php
See https://github.com/woocommerce/woocommerce-gateway-stripe/pull/908#discussion_r304699651 for more context.
cc/ @dechov @allendav
=> Use the Charge ID on Radar-related webhooks if their payload doesn't have a Payment Intent ID

changelog.txt, includes/payment-methods/class-wc-stripe-payment-request.php, readme.txt
See p7bbVw-3f3-p2
The payment buttons only collect the shipping address if the shipping method exists (even if it's free).
The subscriptions, on the other hand, with trial enabled, expect the shipping address to be collected, but no shipping method to be charged for, while at the same time for the shipping method to be saved for later.
So the payment request button does not seem to support the complex subscription functionality.
- Do not show the payment request button when purchasing a trial subscription with shipping.
* Install woo subs and this gateway on a site with https
* Add a card to chrome or use a different method [(see here for docs)](https://stripe.com/docs/stripe-js/elements/payment-request-button#testing)
* The payment button should not appear on the cart page when there's a …
=> Do not show payment request button for shippable trial subscription products

changelog.txt, includes/payment-methods/class-wc-stripe-payment-request.php, readme.txt
See p7bbVw-3f3-p2
- Show payment request button when checking out a variable sub
* Install woo subs and this gateway on a site with https
* Add a card to chrome or use a different method [(see here for docs)](https://stripe.com/docs/stripe-js/elements/payment-request-button#testing)
* The payment button should appear in the cart when checking out a variable subscription
=> Payment request button/variable subs compatibility

changelog.txt, includes/compat/class-wc-stripe-subs-compat.php, readme.txt
Fixes #972.
To test:
* Attempt to reproduce the steps from the issue - the payment should go through
CC @v18 @DanReyLop
=> Don't copy intent id when creating a subs renewal

package.json
Fixes https://github.com/woocommerce/woocommerce-extension-release/issues/22
- Add dot org release config
=> Add dot org release config

includes/abstracts/abstract-wc-stripe-payment-gateway.php, includes/compat/class-wc-stripe-subs-compat.php, tests/phpunit/dummy-data/subscription_signup_response_success.json, tests/phpunit/test-wc-stripe-sub-initial.php
Fixes #935
This PR adds the `setup_future_usage` to intent creation calls when the cart contains a subscription. In order to follow @v18's excellent example of adding tests, I added the `WC_Stripe_Subscription_Initial_Test` test in order to verify the existence of the parameter.
The test covers the `process_payment` method with subscriptions, but only focuses on the PaymentIntent creation call, and not the rest of the method.
1. Add a subscription to the cart and check out.
2. Locate the request log for the payment intent creation in Stripe Dashboard and make sure the 
`setup_future_usage` parameter is set to `off_session`.
3. Add a normal product to the cart and check out.
4. Locate the request log for the payment intent creation in Stripe Dashboard and make sure the …
=> Initial addition of the `setup_future_usage` parameter.

includes/class-wc-gateway-stripe.php
Fixes #965  .
- return early from check intent status if no order
=> fix: return early from check intent status if no order.

includes/class-wc-stripe-webhook-handler.php
Fixes #952 
- Extend the webhook time delta allowed from 1 to 5 minutes
=> Extend webhook time window from 1 to 5 minutes to match Stripe client

changelog.txt, readme.txt, woocommerce-gateway-stripe.php
Fixes #922  .
- Version number updates
- Added changelog entry
=> Update for WooCommerce 3.7

includes/class-wc-gateway-stripe.php
Fixes #1002 .
- This PR avoid assets being enqueued in `order-received` page.
1. Open DevTools
1. Complete an order.
1. Once the order payment is completed and you're redirected to `order-received`, the script should not be enqueued.
=> Don't enqueue assets in order-received page

includes/class-wc-gateway-stripe.php, includes/compat/class-wc-stripe-subs-compat.php
~Marking this as "in progress" because I still need to test this more thoroughly and improve error handling, but it's functionally finished.~ Ready for review now 🎉 
I'm adding some PR comments to point out some potential discussion areas.
To test:
- Create a subscription product.
- Sign up for that subscription using the `4000002760003184` test card.
- After the subscription is active, go to the Edit Order page for the subscription, select `Process Renewal` on `Subscription Actions`, and click the `Update` button.
That should create a renewal order, and attempt to pay for it immediately. SCA will fail, so that renewal order will be in a `failed` state, and will have an `Order Note` telling the user to follow a link. That Order Note will need to be replaced with a real e-mail. because the …
=> Add a way for the user to pass the SCA challenge after a failed renewal

includes/class-wc-gateway-stripe.php
Fixes # .
-
I write a module to handle payment progress for my mobile app, but throw error "Call to a member function empty_cart() on null". So a do a bit fix, please merge a release it.  
`$wc_gateway_stripe                = new WC_Gateway_Stripe();
$_POST['stripe_source']            = $stripe_source;
$_POST['payment_method']            = "stripe";
$payment_result               = $wc_gateway_stripe->process_payment( $order_id );`
=> Fixed Call to a member function empty_cart() on null

includes/abstracts/abstract-wc-stripe-payment-gateway.php, includes/class-wc-stripe-customer.php
Fixes #866 
- Within `prepare_source`, make sure that a Stripe customer always exists. If missing, create one.
- Because a customer object might even be created without a logged in user, gather customer details (first and last billing names) from `$_POST` too.
1. Open an incognito window and add a product to the cart.
2. Check out with a specific email address, which is not in Stripe as a customer yet. Do not register.
3. Go to Stripe Dashboard and check if the customer exists, based on the email. The description of the customer should be like "Name: John Doe , Guest"
=> Always creating a customer object on checkout.

includes/abstracts/abstract-wc-stripe-payment-gateway.php
Fixes #1020.
Fix `WC_Stripe_Payment_Gateway::is_prepaid_card` to work both with `card` and `source` objects instead of just `card` objects, like it did until now.
1. Add the following snippet to a file that will be loaded early enough. A good example is the main plugin file of the gateway.
```php
add_filter( 'wc_stripe_allow_prepaid_card', '__return_false' );
```
2. Try checking out with `5105105105105100`. You should see an error message.
3. Try checking out with a normal card. It should work as expected.
=> Fixing `is_prepaid_card` to make it work with source objects.

includes/class-wc-stripe-api.php
Fixes #1021.
As @dougaitken suggested in https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1021, this PR updates the Stripe API version we are using to the latest, `2019-09-09`.
I looked at [the changelog](https://stripe.com/docs/upgrades#api-changelog), as far as I can tell, there are no upgrades since the previous version, which could interfere with the plugin's functionality. A few smoke tests proved that to be right.
_Note:_ This PR is not too important, so if you think it we should, we can move it to a later version, instead of 4.3.0.
@dougaitken I'm adding you as a reviewer because this change mainly requires smoke tests, and we have some higher-priority PRs which need review at the moment. Any additional help would be appreciated.
=> Upgrading to API version 2019-09-09

includes/admin/class-wc-stripe-admin-notices.php
Fixes #891, Fixes #876.
- Change the style of the updated styles notice _(WooCommerce Stripe - We recently made changes to Stripe that may impact the appearance of your checkout. If your checkout has changed unexpectedly, please follow these instructions to fix.)_ from error to warning.
- Using the `woocommerce_stripe_updated` hook hide the notice
1. When the plugin just got installed (no `wc_stripe_version` option).
2. When the last version of the plugin was `4.1.4` (when the notice was added) or newer, assuming that the message has probably already been seen.
With the plugin installed:
- To simulate a new installation:
1. Navigate to `wp-admin/options.php`
2. Delete the value of the `wc_stripe_show_style_notice` option to make the plugin think that the notice has not been dismissed yet. …
=> Fix the style notice

includes/compat/class-wc-stripe-subs-compat.php
Fixes #1010
1. Make sure that you already have a WC customer with a stripe customer ID (cus_123)
2. Create a new manual subscription using the steps in this video (also listed below as sub-steps of step 2): https://docs.woocommerce.com/document/subscriptions/add-or-modify-a-subscription/
2a. Subscriptions > Create new subscription
2b. Select a customer
2c. Select the Stripe payment method
2d. Enter the customer ID in the customer ID field
2e. Add subscription product
2f. Save
2g. Create parent order
2h. Go to parent order and change status to processing
2i. Renew subscription
3. See that renewing the subscription with just the customer ID entered will work with this branch, but not with plugin v 4.2.4
The problem was that we were sending an empty source string which caused an error, …
=> Do not use empty string as source for payment intent

assets/js/stripe.js, includes/abstracts/abstract-wc-stripe-payment-gateway.php, includes/class-wc-gateway-stripe.php, includes/class-wc-stripe-helper.php, includes/class-wc-stripe-webhook-handler.php, includes/compat/class-wc-stripe-pre-orders-compat.php, includes/compat/class-wc-stripe-subs-compat.php
This PR replaces https://github.com/woocommerce/woocommerce-gateway-stripe/pull/961 and https://github.com/woocommerce/woocommerce-gateway-stripe/pull/997 . Really, it's on top of both those PRs, but because the extensive behaviour change that has been done, I figured this would look better in a single PR, instead of having #961 implement something that this PR would undo.
This PR introduces SetupIntents so the user has a chance to pass a SCA challenge even if the charge is not going to be charged right away. That's important for Subscriptions that have a free trial period, and pre-orders.
Passing the SCA challenge in this way makes it less probable that passing another challenge will be required down the road. We are assuming that most credit cards will behave like this Stripe test card …
=> Add SetupIntents so the customer can confirm an SCA-protected payment even on a free order

includes/admin/class-wc-stripe-admin-notices.php
Fixes #982.
Introduce a dismissable notice to tell the merchant that the extension is SCA-ready. Per @allendav 's advice there are no mentions of compliance.
1. Check out this branch.
2. Open the admin and make sure you see a notice like this:
=> Add a notice for SCA readiness

includes/class-wc-stripe-intent-controller.php
Fixes #932
When introducing `WC_Stripe_Intent_Controller::verify_intent`, I used `woocommerce_get_page_id`, which is deprecated. I did not see a deprecation notice because during AJAX WordPress turns error display off.
After the issue was reported in #932, this PR checks which WooCommerce version is being used and if it is newer than 3.0 or 3.0, the method uses the new `wc_get_page_id` function.
1. Open `<your-website-url>/?wc-ajax=wc_stripe_verify_intent&order=999999`
2. Ensure that the error logs do not contain any deprecated function notices.
=> Fixing a deprecated call to `woocommerce_get_page_id`.

includes/admin/class-wc-stripe-admin-notices.php
Changes a link added in #1012 
- Swapping out the `#section-48` anchor for `#styling` to give a future proof link to the Stripe Styling doc link
=> adding unique anchor for styling

includes/abstracts/abstract-wc-stripe-payment-gateway.php, includes/class-wc-gateway-stripe.php, includes/compat/class-wc-stripe-pre-orders-compat.php, includes/compat/class-wc-stripe-subs-compat.php
Fixes https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1026
This PR ensures compatibility for Pre-Orders + Stripe + SCA. https://github.com/woocommerce/woocommerce-gateway-stripe/commit/f833dd2bc3b8230c32e121533bd53f175a4bd183 has a little refactor that I needed, https://github.com/woocommerce/woocommerce-gateway-stripe/commit/84161caf84320f3a98d3f987d9c754d48f641fe1 has the actual change.
I based this branch on the `alpha.1` branch so we can test it with the most recent changes possible.
To test:
1. Create a Pre-Orderable Product
2. Pre-order it using the 4000 0025 0000 3155 card (requires authentication, but only if it hasn't been "set up").
3. You should get the SCA non-payment modal at checkout.
4. From `wp-admin > WooCommerce > Pre-Orders > Actions > Complete`, select …
=> Migrate the Pre-Orders payment logic to PaymentIntents

includes/compat/class-wc-stripe-email-failed-renewal-authentication.php, includes/compat/class-wc-stripe-subs-compat.php
- Add the `has_authentication_already_failed` method to `WC_Stripe_Subs_Compat`. It is used in `process_subscription_payment` in order to check whether a PaymentIntent is already associated with the order, and if there is one, whether it's awaiting authentication.
- By triggering the `wc_gateway_stripe_process_payment_authentication_required` action in `has_authentication_already_failed`, the `WC_Stripe_Email_Failed_Renewal_Authentication` is being sent during automatic retries.
- `WC_Stripe_Email_Failed_Renewal_Authentication` now prevents all customer-facing emails, sent by automatic retries.
1. Create a Mailtrap account, install the WP extension, and connect them.
2. Go to WooCommerce > Settings > Subscriptions and enable "Enable automatic retry of failed recurring payments ".
3. …
=> SCA Subs: Prevent payment retries and check for authentication instead

includes/class-wc-gateway-stripe.php
To test: run `phpunit` and see that all the tests pass; wait for all travis tests to pass.
=> Fix error in test for initial intent

includes/compat/class-wc-stripe-pre-orders-compat.php
Fixes #949.
This is a follow-up of https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1015, which will be shortly closed.
@tommyshellberg reported that the following error was happening when completing Pre-Orders:
> Stripe Transaction Failed (Keys for idempotent requests can only be used with the same parameters they were first used with. Try using a key other than ...
Initially I opened #1015 in order to fix the issue, but upon further investigation it turned out that I was merely fixing a symptom. Pre-Orders has the following logic when processing payments (off-session):
1. Try payment based on the source, saved in the order's meta.
2. If 1. fails, delete the saved source (or card) ID and retry based on customer ID only, without a source. This should charge the customer's …
=> Fix Pre-Order retries

includes/abstracts/abstract-wc-stripe-payment-gateway.php, includes/class-wc-gateway-stripe.php, includes/class-wc-stripe-customer.php
I was looking at a semi-related issue and I found some code that, after https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1013, is no longer needed.
- The `$set_customer` boolean is unused.
- The `$retry` optional argument on `add_source` is unused.
- The `maybe_create_customer` function is redundant, because a customer object will always be created in the `prepare_source` function, which is called literally one line after `maybe_create_customer`.
=> Remove some dead code related with Customer object creation

includes/class-wc-gateway-stripe.php, includes/compat/class-wc-stripe-subs-compat.php
Fixes https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1037
Steps to reproduce:
- Purchase a subscription with the `4000002760003184` card, then force a renewal.
- You'll get an e-mail prompting you to authorize the renewal (because SCA is required for that card).
- Instead of clicking the authorization link, copy it and open it in an incognito window.
- You'll be presented with the login form. Log in.
In `sca-subs/master`, you'll be redirected to the checkout, and the SCA challenge won't appear.
In this branch, you'll be redirected to a stripped-down version of the "Pay for order" page, and the SCA challenge modal will appear automatically. You'll be able to authorize the payment normally.
=> Preserve the URL parameters after the user logs in

includes/class-wc-stripe-api.php
- Fixes the `WC_Stripe_API::request` method PHP docs.
=> Fix  WC_Stripe_API::request PHP doc

includes/class-wc-gateway-stripe.php, includes/class-wc-stripe-order-handler.php, includes/class-wc-stripe-webhook-handler.php
The rationale and more context is in https://github.com/woocommerce/woocommerce-deposits/pull/306
Fixes https://github.com/woocommerce/woocommerce-gateway-stripe/issues/943 (partially at least)
The change itself is simple. I've changed all the `'blah' === $order->get_status()` checks with the equivalent `$order->has_status('blah')`. That way, the result of that function is filterable so extensions that define their own custom statuses can make it behave the way it should. I don't know which changes are strictly required to make Deposits work, but I don't care, this refactor is simple enough that I just changed all of them.
To test:
- Make sure you have Deposits installed with https://github.com/woocommerce/woocommerce-deposits/pull/306 included.
- Follow the testing steps on …
=> Replaced all the $order->get_status() comparisons with $order->has_status(...) because it's filterable

includes/abstracts/abstract-wc-stripe-payment-gateway.php, includes/compat/class-wc-stripe-subs-compat.php
Fixes #1061. Fixes #1062.
1. Use the `lock_order_payment` and `unlock_order_payment` pair of methods to prevent webhooks from interfering with subscription renewal payments.
2. Modify `lock_order_payment` to work without a particular PaymentIntent, needed because the creation and confirmation of renewal intents is a single API-call process.
3. By doing 1. and 2., prevent payment intent success webhooks from interfering with renewal orders completely. This is not needed, because renewals are headless and wouldn't fail because the customer closed their tab or something similar.
1. Prepare the setup.
1. Create a subscription and purchase it.
2. Make sure webhooks are enabled.
2. Reproduce the bug
1. Checkout `master`.
2. In `WC_Stripe_Subs_Compat::process_subscription_payment`, add a `sleep( …
=> Fix duplicate payment notifications

readme.txt, woocommerce-gateway-stripe.php
Fixes #999
I did a basic smoke test (buying a product using an SCA-required card, a regular card, buying a subscription) using WooCommerce 3.8 and WordPress 5.3 RC4 (the latest version at the moment of writing this). Everything worked.
I've taken a look at WooCommerce 3.8's changelog, and I don't see anything that could potentially impact us. There's some CSS tweaks in WP-Admin, but that just means that the Setting pages look prettier.
=> Declare WordPress 5.3 and WooCommerce 3.8 compatibility

includes/compat/class-wc-stripe-sepa-subs-compat.php, includes/compat/class-wc-stripe-subs-compat.php
Fixes #764 
I've split https://github.com/woocommerce/woocommerce-gateway-stripe/pull/874 into 2 PRs, to make it easier to review.
This one refactors a bit how the "`Update the Payment Method used for all of my active subscriptions`" checkbox is displayed in the `Add Payment Method` screen, to use the `woocommerce_form_field` helper function.
It also adds a `wc_stripe_save_to_subs_checked` filter (`false` by default) that controls if said checkbox should be checked/unchecked by default.
To test:
- Have some active subscriptions in your account.
- Go to `My Account -> Payment Methods -> Add payment method`.
- See that the checkbox is unchecked.
- Add this filter anywhere that's run on every page load (like `functions.php`): `add_filter( 'wc_stripe_save_to_subs_checked', '__return_true' );` …
=> Add a filter so the checkbox for updating the payment method used in all subscriptions can be checked by default

includes/compat/class-wc-stripe-sepa-subs-compat.php, includes/compat/class-wc-stripe-subs-compat.php
I've split #874 into 2 PRs, to make it easier to review.
By default, only active subscriptions' payment methods are updated when you add a new payment method and tick the "`Update the Payment Method used for all of my active subscriptions`" checkbox. This PR adds a filter so the change can affect subscriptions on other statuses.
To test:
- Have some active, on-hold, or pending subscriptions in your account.
- Go to `My Account -> Payment Methods -> Add payment method`.
- Add a new payment method, remember to tick the checkbox.
- See that only active subscriptions have the new payment method.
- Add this filter anywhere that's run on every page load (like `functions.php`): `add_filter( 'wc_stripe_update_subs_payment_method_card_statuses', function( $statuses ) { return [ 'active', …
=> Add filter so the payment method can be updated for all subscriptions, not only active ones

includes/payment-methods/class-wc-stripe-payment-request.php
Fixes #1060 .
Make the `ajax_add_to_cart` method of `WC_Stripe_Payment_Request` treat subscriptions and variable subscriptions as products and variable products respectively.
__Note:__ The class already checks whether free trials are supported for a product, and if yes, hides the payment request buttons.
Open the product page of a subscription and/or variable subscription and try to purchase it through a payment request. Without this PR the purchase fails because of an empty cart, while with this PR it should work well.
=> Ensuring subscriptions are added to the cart during payment requests.

includes/payment-methods/class-wc-stripe-payment-request.php
Fixes #819.
- Uses the existing WC()->session and instance instead of creating a new one to prevent edge cases and improve plugin compatibility
- Remove version check for WC 3.3+, doesn't _seem_ to be needed
=> Changed how session are handled to prevent a 2 session situation

changelog.txt, includes/class-wc-gateway-stripe.php, readme.txt
Fixes #1124 .
Refactoring `WC_Gateway_Stripe::complete_free_order()` to call `get_return_url` immediately before returning. This way other WooCommerce extensions can be aware of SetupIntents, which used to be prepared before determining the return URL.
Purchase a subscription with a free trial while using a card, which triggers SCA challenges. It should still be fully functional.
Additionally, feedback and testing from @xlplugins (who reported the issue) are welcome.
=> Refactor `complete_free_order` for compatibilty with other plugins

changelog.txt, includes/abstracts/abstract-wc-stripe-payment-gateway.php, includes/admin/class-wc-stripe-admin-notices.php, includes/admin/class-wc-stripe-privacy.php, includes/class-wc-gateway-stripe.php, includes/class-wc-stripe-customer.php, includes/class-wc-stripe-order-handler.php, includes/class-wc-stripe-webhook-handler.php, includes/compat/class-wc-stripe-sepa-subs-compat.php, includes/compat/class-wc-stripe-subs-compat.php, includes/payment-methods/class-wc-gateway-stripe-sepa.php, languages/woocommerce-gateway-stripe.pot, readme.txt
Fixes #1092.
Many merchants are experiencing errors, related to missing customers. Those errors can be caused by multiple factors:
1. The Stripe account was changed.
2. The customer was manually deleted in Stripe.
3. The extension is used in a multisite network.
While No. 2 is a conscious decision, 1 & 3 are addressed by this PR by the following changes:
H/T @thenbrent for suggesting those APIs!
The `*_user_option` APIs are built on top of user meta APIs, but add blog-specific prefixes to meta keys in order to isolate bits of data for a specific site.
`get_user_option()` also has a built-in fallback in case a setting is specified globally, but not for the given site. This means that the new version of the gateway will not degrade UX any further, but might improve it with time. There is …
=> Add multisite support and notify merchants after acccount changes

includes/admin/stripe-eps-settings.php, languages/woocommerce-gateway-stripe.pot
@gerdneuman opened https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1127 with a meaningful fix, but did not commit a parsed POT file.
It's a simple translation fix, so I'll allow myself to immediately merge the PR.
=> Fixing a typo (origin PR 1127) with updated translations translations

includes/compat/class-wc-stripe-sepa-subs-compat.php, includes/compat/class-wc-stripe-subs-compat.php
Fixes #1072 
Save the Stripe customer ID on the subscription when the customer adds a new payment method via the **My Account > Payment methods** screen and opts to update all their active subscriptions. 
To test: 
1. Purchase a subscription through a non-Stripe payment method (eg PayPal)
2. Go to **My Account > Payment Methods** and add a new Stripe payment method
3. Be sure to select the option for "Update the Payment Method used for all of my active subscriptions (optional)."
4. Go to the subscription and click "Billing Details" to edit
5. On `master` see that [no Customer ID token has been saved to the subscription.](https://d.pr/i/b9YerW)
6. After replicating on this branch you should see the [customer token is set](https://d.pr/i/KNW0h8).
=> Save the customer ID when updating all subscription payment methods

includes/abstracts/abstract-wc-stripe-payment-gateway.php, includes/class-wc-gateway-stripe.php, includes/class-wc-stripe-api.php, includes/class-wc-stripe-order-handler.php, tests/phpunit/test-wc-stripe-level-3-data.php
Fixes #860.
This PR sends level3 data in the following functions:
1. update_existing_intent
- Can be tested by checking out with a failing credit card (e.g. `4000000000000069`) and then checking out with a working card.
2. confirm_intent
- Can be tested by checking out normally.
3. create_and_confirm_intent_for_off_session
- Can be tested by renewal a subscription (Edit Subscription screen > Subscription actions > Renew subscription).
4. prepare_intent_for_order_pay_page
- Can be tested by purchasing a subscription using card that requires 3DS authentication (e.g. `4000 0027 6000 3184`), then renewing the subscription, and then using the authorize link sent to the customer to authenticate the subscription.
5. capture_payment
- Can be tested by unchecking the option "Capture charge …
=> Add function to generate level 3 data from order

changelog.txt, includes/abstracts/abstract-wc-stripe-payment-gateway.php, includes/class-wc-gateway-stripe.php, readme.txt
Fixes #1110.
When a user is logged in during checkout and saving a card to the account using the checkbox "Save payment information to my account for future purchases.", an error can happen while we `prepare_source`.
If we get an error back from Stripe during `prepare_source`, we'll throw an exception using the localized error message instead of the original error message we get back from Stripe.
=> Localize error message for save card on checkout

includes/payment-methods/class-wc-stripe-payment-request.php
Fixes https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1138
In this PR:
- I removed some `< WC 3.0` checks while I was at it, it's long overdue.
- Properly unescape attributes that come in the `$_POST` payload before using them to find a product variation.
- Correctly configure the payment request with the correct product variation on first page load (not only on AJAX updates).
Testing instructions in https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1138
@vbelolapotkov 
Thanks @hardipparmar-multidots for your contribution! It was much easier to tweak your solution than to having to figure out what's wrong for ourselves :) Would you mind checking if these changes fix your issue?
=> Fix Payment Request issue when product attribute has quotes

.gitignore, includes/admin/class-wc-stripe-admin-notices.php, woocommerce-gateway-stripe.php
Fixes #832 .
- Add WP-Admin alert for users running WC < 3.0
1. Install WC < 3.0 and add activate plugin (I was able to download one [here](http://pluginsroom.com/plugins/woocommerce)).
Or update min version in `woocommerce-gateway-stripe.php` => `define( 'WC_STRIPE_FUTURE_MIN_WC_VER', '3.0' );` to be above current WC version.
2. Go to WP Admin. Alert should be displayed:
=> Add alert for end of support WC < 3.0 in future releases

includes/abstracts/abstract-wc-stripe-payment-gateway.php, includes/class-wc-stripe-customer.php
Fixes #1128 .
- During Checkout, if a user is logged in and performed the checkout before, the associated customer object ID will be stored in the site DB and the object updated in Stripe.
- If the ID and the merchant's Stripe account mismatch for any reason, the checkout will fail on the update step.
- This PR recreates the customer object in the above scenario rather than failing straight away. 
- If the failure occurs more than once, then the error will be shown.
1. Have two Stripe accounts ready
1. Create a WP/Woo user account for a customer (you can use incognito mode for convenience)
1. Use the keys from one Stripe account on your site
1. Place an order as the user from step 2.
1. Change the keys to another Stripe account (Check user meta table in your db, it should contain …
=> Fix "no such customer" error on checkout

includes/class-wc-gateway-stripe.php
Fixes #1139 
Quick fix. The issue was not triaged but it was trivial.
To test:
- Downgrade the WooCommerce Subscriptions to a version earlier than `2.6.0`.
- Go to `My Account -> Subscriptions`, and click in a subscription number to go to its details page.
Expected behaviour: 🎉 
Behaviour in `master`: 💥 
Behaviour with this PR: 🎉
=> Fix crash when used with WooCommerce Subscriptions <2.6

readme.txt, woocommerce-gateway-stripe.php
Fixes #1123 
Fixes #1148
I updated WP to 5.4 and Woo to 4.0.1 and did some smoke testing (new transactions, subs renewal, refunds) and everything worked.
=> Bump "tested up to" headers

includes/compat/class-wc-stripe-sepa-subs-compat.php, includes/compat/class-wc-stripe-subs-compat.php
Fixes #1094 
- Replaced `WP_Error` with `WC_Stripe_Exception` to be in line with the rest of the function
Despite the scary repro steps below, this PR is just bringing the code in line with the rest of the function. WP_Errors would not be handled at all and are just an early return, while the Exceptions would be logged in [here](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/323cf377574cd942b48647436bc3af315c4e5449/includes/compat/class-wc-stripe-subs-compat.php#L361) and the order would be marked as failed.
* Enable logging in this extension
* Purchase a subscription
* In wp-admin, open the subscription
* Under actions, select "Create pending renewal order"
* In the database, delete `_stripe_customer_id` from `wp_postmeta` for that new renewal order ID
* Go back to the …
=> Do not return WP_Error when processing sub renewals

includes/abstracts/abstract-wc-stripe-payment-gateway.php, tests/phpunit/test-wc-stripe-payment-gateway.php
Fixes #1066 .
The issue is caused by error object returned from Stripe API when test mode payment intent associated with the order is fetched in the live mode. The error object was mistakenly treated as an intent object (with empty id). Hence further POST request is sent to the wrong URL `payment_intents/` and fails.
To fix the issue extra check of the response object is added. Errors are logged and `false` is returned instead of payment intent in such cases.
There is no known reliable way to reproduce the issue.
Added some unit tests so running PHP unit tests is the only way of testing at the moment.
See #1163 for instructions on setting up and running unit tests.
=> Fix transactions failing with trailing slash

changelog.txt, languages/woocommerce-gateway-stripe.pot, package-lock.json, package.json, readme.txt, woocommerce-gateway-stripe.php
* Updated the changelogs
* Updated the version in plugin, readme and package.json
* Regenerated the .pot file
* Had to bump the sass dependency because it blocked the npm build on the latest Node/OSX. No JS/CSS files have been affected, so it shouldn't block the release
=> Roll 4.3.3 release

includes/class-wc-gateway-stripe.php, includes/payment-methods/class-wc-gateway-stripe-alipay.php, includes/payment-methods/class-wc-gateway-stripe-bancontact.php, includes/payment-methods/class-wc-gateway-stripe-eps.php, includes/payment-methods/class-wc-gateway-stripe-giropay.php, includes/payment-methods/class-wc-gateway-stripe-ideal.php, includes/payment-methods/class-wc-gateway-stripe-multibanco.php, includes/payment-methods/class-wc-gateway-stripe-p24.php, includes/payment-methods/class-wc-gateway-stripe-sepa.php, includes/payment-methods/class-wc-gateway-stripe-sofort.php
Performance of `wc_get_order_id_by_order_key` is extremely bad on large databases. This PR changes all uses of this to use the order-pay query var which is available and already gets you the order ID.
=> Improve performance on order pay screen.

includes/class-wc-stripe-customer.php
Returns the caching layer to the `WC_Stripe_Customer::get_sources()` function.
This function used to cache the response in a transient, but it was removed in commit [`0c3c1be`](https://github.com/woocommerce/woocommerce-gateway-stripe/commit/0c3c1be41987a9d9976c50cf6560c7d41e409ec7#diff-f8dd0b04c52dc566825dead0a3b8b84c). It wasn't fully removed though; there is still a `get_transient()` which remained and the `clear_cache()` function which still runs. 
Looking at the issue that 0c3c1be fixed (#478 ), I don't think the cache layer was the problem. Please correct me if I'm wrong 🙂 
I noticed on the **My Account > Subscriptions tab**, it was taking about 8-10 seconds to load the page. Looking into why it was taking that long, I noticed there were 8 HTTP requests all retrieving information …
=> Returns a caching layer to WC_Stripe_Customer::get_sources()

includes/abstracts/abstract-wc-stripe-payment-gateway.php, includes/admin/class-wc-stripe-admin-notices.php, includes/admin/stripe-settings.php, includes/class-wc-gateway-stripe.php, includes/payment-methods/class-wc-stripe-payment-request.php
Fixes #1151
- https://github.com/woocommerce/woocommerce-gateway-stripe/commit/e1af6e1dc0f0c1ae1cb8face0ec2a72f23e73021 Don't render anything in the frontend if the keys don't have the expected format.
- https://github.com/woocommerce/woocommerce-gateway-stripe/commit/dd37cd26a6719500f18b074a70deadeda2ec5bc0 Show an error notice when trying to save a key with an incorrect format. Merchants usually have "admin notices blindness", but this was the easiest solution I could come up with. Incorrect keys won't be saved but the rest of the settings will. Can you think of a better approach, like letting the merchant save the keys and having a persistent "WRONG KEYS" admin notice? Or this is fine?
- https://github.com/woocommerce/woocommerce-gateway-stripe/commit/96a7880ba2b627725e2858e1042ab5662bc …
=> Prevent exposing secret keys in the frontend

includes/abstracts/abstract-wc-stripe-payment-gateway.php
In the `if ( ( $user_id && $this->saved_cards && $maybe_saved_card ) || $force_save_source ) {` block
In the **else** case, user wishes to use stripe_token for checkout, **without** creating a stripe customer.  It works flawlessly.
`$source_id` is set to $stripe_token. This is set, so that [`if ( empty( $prepared_source->source ) ) `](https://github.com/SK8-PTY-LTD/woocommerce-gateway-stripe/edit/master/includes/class-wc-gateway-stripe.php#L705) can pass.
Similarly, In the **if** case, $source_id should **also be set**, but it is missing. 
This resulted a unnecessary WC_Stripe_Exception. [class-wc-gateway-stripe.php](https://github.com/SK8-PTY-LTD/woocommerce-gateway-stripe/edit/master/includes/class-wc-gateway-stripe.php#L705) will throw an WC_Stripe_Exception.
Fixes # .
- …
=> Added Missing $source_id, when creating Stripe Customer & Saving Token as $source

.travis.yml, includes/abstracts/abstract-wc-stripe-payment-gateway.php, includes/admin/class-wc-stripe-admin-notices.php, includes/class-wc-gateway-stripe.php, includes/class-wc-stripe-helper.php, includes/class-wc-stripe-intent-controller.php, includes/class-wc-stripe-logger.php, includes/class-wc-stripe-order-handler.php, includes/class-wc-stripe-sepa-payment-token.php, includes/class-wc-stripe-webhook-handler.php, includes/compat/class-wc-stripe-pre-orders-compat.php, includes/compat/class-wc-stripe-sepa-subs-compat.php, includes/compat/class-wc-stripe-subs-compat.php, includes/payment-methods/class-wc-gateway-stripe-alipay.php, includes/payment-methods/class-wc-gateway-stripe-bancontact.php, includes/payment-methods/class-wc-gateway-stripe-eps.php, includes/payment-methods/class-wc-gateway-stripe-giropay.php, includes/payment-methods/class-wc-gateway-stripe-ideal.php, includes/payment-methods/class-wc-gateway-stripe-multibanco.php, includes/payment-methods/class-wc-gateway-stripe-p24.php, includes/payment-methods/class-wc-gateway-stripe-sepa.php, includes/payment-methods/class-wc-gateway-stripe-sofort.php, includes/payment-methods/class-wc-stripe-payment-request.php, templates/emails/failed-preorder-authentication.php, tests/phpunit/test-wc-stripe-level-3-data.php, tests/phpunit/test-wc-stripe-payment-gateway.php, tests/phpunit/test-wc-stripe-sub-initial.php, tests/phpunit/test-wc-stripe-sub-renewal.php, woocommerce-gateway-stripe.php
Fixes #833.
- Display a non-dismissable banner that versions of WooCommerce less than 3.0 are no longer supported and block the plugin from loading when WooCommerce < 3.0
- Remove pre 3.0 compatibility code, including `pre_3_0_get_intent_from_order` and `is_pre_30` functions
*Header and docs will be updated by https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1183* 
**Using a pre 3.0 version of WC**
1. Make sure this notice is displayed
2. Make sure the plugin is not loaded (it should not be available for checkout or be listed under WooCommerce > Settings > Payments)
**Using a post 3.0 version of WC**
1. Make sure the plugin is active
2. Check if automated tests are passing
3. Run purchases using subscriptions and different payment methods
=> Remove support for WC versions before 3.0

includes/abstracts/abstract-wc-stripe-payment-gateway.php
Fixes #1168 .
This PR casts shipping amount and shipping tax amount to float before adding them, to avoid the warning "A non-numeric value encountered" when calculating the shipping amount for level 3 data.
=> Level 3 data: Cast shipping amounts to float when adding

composer.json, composer.lock, includes/payment-methods/class-wc-stripe-payment-request.php, phpcs.xml.dist, tests/phpunit/test-wc-stripe-payment-request.php
Fixes #755, fixes #1177 .
When `requestShipping` option is enabled on payment request the following happens:
1. When on a cart page and shipping options selected (address and method).
2. User clicks Apple Pay / Google pay button (doesn't matter to be honest).
3. Popup is opened and default shipping address (might be the same or different) configured in Apple Pay is applied. Hence new shipping options for a selected address should are fetched.
4. Previously selected shipping cost displayed while new shipping methods are being fetched.
5. Once fetched, first in the list shipping option is selected by default.
I.e. step 3 triggers a shipping address change flow in the same way as normal cart UI does.
- Keep the previously selected shipping method by sorting shipping options.
Preparation:
* …
=> Update shipping methods request

includes/payment-methods/class-wc-stripe-payment-request.php
Fixes #1033 .
The change is extremely small, but allows customers to use the abbreviation of their state when using payment requests. To understand this:
So far the request class was always expecting full state names, which would then get converted to the abbreviation. With this change, it will detect that the value is already an abbreviation and not try to convert it.
Perfectly described in [the issue](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1033) by @dougaitken!
=> Allowing state abbreviations to be used in payment requests

woocommerce-gateway-stripe.php
Fixes #1208.
- Update - Move `Docs` and `Support` links on plugin page from action section (below plugin title) to meta section (inline with plugin version number).
**Before:**
**After:**
=> #1208: Move links from action to meta section

includes/payment-methods/class-wc-stripe-payment-request.php
Fixes #1222
This is an alternative approach to #1223. The end result is exactly the same (the filter name is the same, its behaviour is the same), but it doesn't flood the debug log if the filter returns `false`.
This is just a slightly different approach to an existing PR that occured to me while reviewing it, so I don't think a second review is needed.
- Added a new filter named `wc_stripe_show_payment_request_on_cart`. If that filter returns `true` (the default), `Payment Request` buttons (G Pay, 🍎 Pay, etc) will be displayed in the cart. If `false`, they won't be displayed in the cart. There are already equivalent filters for the [checkout](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/19e5f4a47d4ad94d4d367a588b3cd4b227c9f80d/includes/payment-methods/class-wc-stripe-pa …
=> Introduce a new filter to manage the display of payment request buttons in cart

woocommerce-gateway-stripe.php
Fixes #1221 .
- Bumps the tested up to version for WooCommerce to version 4.2.
=> Bump 'WooCommerce Tested Up To' to version 4.2

languages/woocommerce-gateway-stripe.pot, package-lock.json, package.json, readme.txt, woocommerce-gateway-stripe.php
I'm still working on merging some of the ready to merge PRs, which is why the changelog and POT files aren't ready yet.
=> Create release 4.5.0

includes/class-wc-stripe-order-handler.php
Fixes #1260  .
- Adds additional metadata to order status changes when using this payment method
- Enable tracking (wp-admin > WooCommerce > Settings > Advanced)
- Complete some orders (test works fine) using the Stripe payment method
- Ensure Tracks receives the wcadmin_orders_edit_status_change  events and the metadata is added (admin email, test/live, default country and plugin version)
=> Filter additional metadata for order status changes

changelog.txt, languages/woocommerce-gateway-stripe.pot, package-lock.json, package.json, readme.txt, woocommerce-gateway-stripe.php
Fixes #1286 
Fixes #1284 
- Remove the country check
- Roll to 4.5.2
- `npm run build`
- Install the resulting plugin ZIP on a test site for an not-yet-officially supported country, e.g. India
- Ensure the plugin shows "4.5.2" as its release version
- Ensure the payment form displays on checkout
- Change the store location to an officially supported country, e.g. the United States
- Ensure you can complete a test purchase.
fyi @bmccotter 
=> Remove country check, roll version to 4.5.2

changelog.txt, includes/admin/stripe-settings.php, languages/woocommerce-gateway-stripe.pot, package-lock.json, package.json, readme.txt, woocommerce-gateway-stripe.php
Fixes #1308
- Updates the payment request setting description to include a deep link to the Apple Pay settings on the merchant's Stripe dashboard
- Bumps the versions to 4.5.3
- Make sure all links function correctly in the description, not just the new one
- Make sure the new link drops you on https://dashboard.stripe.com/settings/payments/apple_pay (you may need to log in, and then it will take you there if you weren't logged in already)
cc @bmccotter 
=> Update payment request button description to include link to dashboard

composer.json, includes/abstracts/abstract-wc-stripe-payment-gateway.php
Fixes #1274. Replaces #1273
- Adds additional filter for the off session payment intent requests.
=> Add off session payment intent filter

tasks/release.js
Fixes #1311 
- Adds the apple association file to the build ZIP
- Adds the uninstall file to the build ZIP
- composer install
- composer update
- npm install
- npm run prebuild
- npm run build
- npm run build:release
- Make sure release/woocommerce-gateway-stripe.zip includes both files (in the root of the ZIP)
=> Add apple association and uninstall files

includes/class-wc-stripe-apple-pay-registration.php
Fixes https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1313
Hooks into updates of the secret key to **trigger domain verification** even when onboarding is done via an entry point other than the Settings screen (namely the Stripe onboarding task in WooCommerce core).
Also adds this to the plugin update mechanism, for those who already did the setup but are just missing the domain verification piece.
To test, can install this version on a new instance, and then:
- Ensure that domain does not appear [on Dashboard](https://dashboard.stripe.com/settings/payments/apple_pay)
- Connect Jetpack + WooCommerce Services (e.g. via end of Setup Wizard)
- Go to Task List » Set up payments » Stripe (Set up)
- "Connect" Stripe account via OAuth
- Observe that domain now appears [on …
=> Perform Apple Pay domain verification on setup outside of settings screen

includes/admin/stripe-settings.php
Reworks the Apple Pay configuration link in the Payment Request description as a parenthetical (but keeping the Dashboard link), as domain verification is done automatically.
`master` branch:
This branch:
=> Tweak wording of Apple Pay Stripe Dashboard link

includes/abstracts/abstract-wc-stripe-payment-gateway.php, includes/compat/class-wc-stripe-subs-compat.php
Fixes (edit: _not entirely_) https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1102
Fixes https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1181
Allows `pm_` payment method IDs to be submitted as subscription payment method source (on Edit Subscription screen) and charged for renewals. (Other behaviors depending on `src_` IDs are unchanged.)
Adapted from solution offered in the comments of https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1181 (thanks @nsandrew).
To test:
- With WooCommerce Subscriptions activated…
- Create Customer with attached Payment Method, e.g. with cURL:
```bash
curl https://api.stripe.com/v1/payment_methods \
-u sk_test_****: \
-d type=card \
-d "card[number]"=4242424242424242 \
-d "card[exp_month]"=02 \
-d …
```
=> Allow migrated Payment Methods to be charged on subscription renewal

includes/abstracts/abstract-wc-stripe-payment-gateway.php
Fixes #1266
- Sets the `shipping` property on payment requests when available in the order
- Make a payment
- Open the payment in Stripe dashboard
- Confirm the shipping address is present
=> Add shipping address to payment requests

includes/class-wc-stripe-apple-pay-registration.php
Fixes #1240 .
- Combines the "Not a valid URL" notice with the "Apple Pay domain verification failed" notice.
- The new notice shows the "Not a valid URL" message in the notice if it exists, otherwise it shows a more generic notice without the message.
=> Fix the "Not a valid URL" notice

changelog.txt, includes/admin/stripe-alipay-settings.php, includes/admin/stripe-bancontact-settings.php, includes/admin/stripe-eps-settings.php, includes/admin/stripe-giropay-settings.php, includes/admin/stripe-ideal-settings.php, includes/admin/stripe-multibanco-settings.php, includes/admin/stripe-p24-settings.php, includes/admin/stripe-sepa-settings.php, includes/admin/stripe-sofort-settings.php, includes/payment-methods/class-wc-gateway-stripe-alipay.php
Fixes #1340
- Allow Alipay when store currency is set to CNY
=> Allow Alipay when store currency is set to CNY

changelog.txt, includes/class-wc-stripe-customer.php
Supersedes #1304 since I can't make direct changes to that PR. Thank you @mbeinder for your PR!
Description copied from there.
<hr />
- `$billing_full_name` is derived from `$billing_first_name` and `$billing_last_name` filling the `name` field in stripe on the customer object.
=> Add full name to stripe customer

changelog.txt, includes/abstracts/abstract-wc-stripe-payment-gateway.php
- Add `site_url` to all transactions, not just recurring ones.
=> Add site_url to all transactions, not just recurring

includes/admin/class-wc-stripe-inbox-notes.php, includes/class-wc-stripe-apple-pay-registration.php, woocommerce-gateway-stripe.php
Fixes #1350 
Adds a WooCommerce inbox note targeting the case when domain verification was attempted but did not succeed.
Exact copy TBD. Could perhaps use a bit more thought into the logic for when it appears.
**To test:**
[…]
=> Add Inbox note for Apple Pay domain verification if needed

includes/class-wc-stripe-apple-pay-registration.php, woocommerce-gateway-stripe.php
Fixes #1355 
Rather than copying the domain association file (and having to update it if it's changed), add a rewrite rule to serve it from its original location in the plugins directory.
The behavior of this module is modified to only perform the domain verification when settings are updated (and properly configured), and when the plugin is updated. The rewrite rule is flushed right before the domain registration request to ensure the domain association file will be served.
**Testing instructions:**
- On a fresh WooCommerce install, install & activate Stripe plugin on this branch
- Configure gateway
- (Either…) Go through the Task List » Set up payments » Stripe "Set up" flow
- (Or…) Enable the Stripe gateway on the WooCommerce » Settings » Payments » Stripe screen (leaving Payment …
=> Serve Apple Pay domain association file via rewrite rule

includes/admin/class-wc-stripe-inbox-notes.php, includes/class-wc-stripe-apple-pay-registration.php
Fixes #1351
Shows a marketing Inbox note **a day after** successfully enabling Apple Pay and automatic domain verification (for US):
The "Apple Pay domain verification needed" note (implemented previously in #1350) is now referred to in code as the "failure note", while the "Boost sales this holiday season with Apple Pay!" is called the "success note" or "marketing note". A subsequent release (after the holidays) will replace the success note with a different one.
Note: https://github.com/woocommerce/woocommerce-gateway-stripe/commit/ee65be12f80eec98286d5244cba3862646fb35c2 fixes a bug where the failure note shows even in success case, overlooked in #1337.
For testing, I changed the delay from `DAY_IN_SECONDS` to `45` so that I could verify the appearance of the note in under a minute …
=> Show Apple Pay holiday marketing note on setup success

assets/js/stripe-payment-request.js
Fixes https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1364
Makes sure phone number value is available before processing it for passing to the payment request, so that there is no JS error (and aborted payment request) in the case when the phone number is not required in checkout.
**To test:**
With Apple Pay set up, set Customizer » WooCommerce » Checkout » Phone field to "Optional" or "Hidden" (see also testing instructions in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1317). Go through the whole Apple Pay payment flow and verify that it completes.
=> Avoid Apple Pay payment failure on non-required phone field

woocommerce-gateway-stripe.php
Fixes https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1368
When settings are initially saved, they should have all settings values set, as is assumed throughout the code. Adds a filter to ensure this by filling in defaults for missing settings on initial save.
To test, follow instructions in https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1368 but verify that no admin notice shows up and observe **behavior intended by default settings** [[source](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/includes/admin/stripe-settings.php)] rather what's described in the issue.
=> Provide defaults for missing settings on initial gateway settings save

changelog.txt, includes/admin/class-wc-stripe-inbox-notes.php
Fixes #1371
Adds try/catch around Data Store loads, to prevent fatal error being thrown on that call.
Unfortunately I'm unable to reproduce the error, so cannot confirm first-hand at this point whether this fix solves the fatal.
=> Guard against fatal error on Inbox data store load

includes/class-wc-stripe-payment-tokens.php, includes/compat/class-wc-stripe-sepa-subs-compat.php, includes/compat/class-wc-stripe-subs-compat.php, woocommerce-gateway-stripe.php
Fixes #1353 
- Ensure that optional function arguments follow required ones (https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1356/commits/3b18c73cda6a0c1af7482d35aa3eb2422157c3be)
- Avoid "magic method must have public visibility" warning (https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1356/commits/a94ead617160a9cff8501f4ead962804409a860d)
=> Code tweaks for PHP 8 compatibility

tasks/release.js
* Set maximal compression level for release zip-file (reduces the size from 5 MB to 4.5 MB for WCPay)
* Run `npm run build:release` and ensure you can open the archive and see it's contents
=> Set max compression level for zip file produced by build:release.

changelog.txt, composer.json, composer.lock, readme.txt
Update `composer.json` and `composer.lock` so that they're compatible with the latest version of Composer.
1. Run `composer self-update` to get the latest version of Composer.
1. Run `composer install`.
And make sure no errors occur.
=> Update packages for composer v2 compatibilty

changelog.txt, includes/admin/class-wc-stripe-inbox-notes.php, languages/woocommerce-gateway-stripe.pot, readme.txt
Issue: Link to the GitHub issue this PR addresses (if appropriate).
Fixes #1388 
Description: Adds a scheduled event for Dec-22 to refresh the title (dropping the reference to the holiday) on any un-actioned Apple Pay notes.
- Navigate to wp-admin > WooCommerce
- Open your inbox
- Verify you have a "Boost sales this holiday season with Apple Pay!" note. Make note of the "x minutes ago / x days ago / whatever"
- Install and activate this branch
- Install and activate the Crontrol plugin
- Navigate to wp-admin > Tools > Cron Events
- Search Hook Names for 2020
- Make sure you have a wc_stripe_apple_pay_2020_cleanup Hook scheduled to run at 2020-12-22 00:00:00 UTC
- Make sure it has an action of WC_Stripe_Inbox_Notes::cleanup_campaign_2020()
- Run it manually (hover over the hook name and …
=> Refresh unactioned Apple Pay notes after 2020 Dec 22

changelog.txt, includes/admin/class-wc-stripe-inbox-notes.php, readme.txt
Fixes #1414
The problematic line from that issue is here:
https://github.com/woocommerce/woocommerce-gateway-stripe/blob/4.5.5/includes/admin/class-wc-stripe-inbox-notes.php#L121
Using `new WC_Admin_Note()` makes a call to `\WC_Data_Store::load( 'admin-note' )` which can result in an Exception raised when 'admin-note' in an invalid type. You can make it an invalid type by [using a filter](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1372#issuecomment-728814679).
For this PR I checked for all uses of:
- WC_Admin_Note
- WC_Admin*
- WC_Data*
If I'm missing any other problematic areas related to WC Admin, let me know so they can be fixed.
=> Catch possible WC_Admin_Note exceptions

includes/abstracts/abstract-wc-stripe-payment-gateway.php
Fixes #1403
When a customer pays for a fail subscription renewal using an SCA card, this PR makes sure that this card can be used for future subscription renewal.
1. As a customer, check out with a subscription using `4242424242424242`
2. Add `4000002500003155` card to payment methods with the checkbox `Update the Payment Method used for all of my active subscriptions. (optional)` checked (no SCA modal is shown)
3. As admin, renew subscription (under Edit Subscription > Subscription actions box > "Process renewal" in dropdown > click "Update" button)
4. See order fails
5. Use customer link to complete order with SCA card `4000002500003155` (under Edit Order > "Customer payment page →")
6. See order succeeds
7. Try to renew order again (using admin)
8. See order fails (and when this branch …
=> Mark existing intent for future use if renewal

readme.txt
I just noticed that I accidentally broke the link to the full changelog in the 4.5.5 release. This PR updates the readme to fix the link.
=> Fix broken link to changelog in readme

changelog.txt, includes/compat/class-wc-stripe-sepa-subs-compat.php, includes/compat/class-wc-stripe-subs-compat.php, readme.txt
Fixes #1419 
Description: Replaces the manual setting of post meta when updating subscriptions methods with a call to `WC_Subscriptions_Change_Payment_Gateway::update_payment_method`. This should allow the Subscriptions extension to handle the payment method update, including adding notes to the order.
- Purchase a subscription
- Verify the subscription appears in the admin panel and check the notes added to it
- Go to My Account and add a new Stripe payment method. **Make sure `Update the Payment Method used for all of my active subscriptions.` is checked**
- After adding a new method, refresh the subscription in the admin panel
- A note should be present:
=> Use sub's update_payment_method function

includes/admin/class-wc-stripe-inbox-notes.php
Fixes #1429
I searched using the regex `return[^\s]*;` for any other return statements missing a space (none found).
=> Fix missing space in return statement

changelog.txt, includes/admin/stripe-settings.php, includes/class-wc-gateway-stripe.php, includes/class-wc-stripe-helper.php, languages/woocommerce-gateway-stripe.pot, package-lock.json, readme.txt, tests/phpunit/test-wc-stripe.php
Fixes #1262 .
- Adds / ( ) { and } to disallowed descriptor character list
- Attempt to add those characters to your descriptor. Ensure they are removed for you.
=> Add to disallowed descriptor character list

changelog.txt, includes/abstracts/abstract-wc-stripe-payment-gateway.php
Issuing a refund where the refund reason is >500 characters will return an error in Stripe, but WC mostly behaves like the refund worked. This change trims the refund reason down to fit within Stripe's limit.
Fixes #1446
1. Start with a test WC site + Stripe in test mode.
2. Place an order for a product.
3. Refund the full amount of the order. In the Reason box, insert some dummy text greater than 500 chars in length.
4. Issue the refund.
5. Notice the order status changes to Refunded.
6. Click the txn ID at the top to go directly to the Stripe page for the transaction.
7. Scroll down to the "Events and logs" section.
8. There will be an error indicating that the refund reason "must be a string under 500 characters."
9. Apply the change in this pull request.
10. Repeat this same test with …
=> Trim the refund reason to a max of 500 characters

includes/class-wc-stripe-webhook-handler.php
Issue: https://wordpress.org/support/topic/stripe-webhooks-failing/
Fixes https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1136
Problem
* When multiple applications or site instances are connected a to Stripe account, then the signature of incoming events can be invalid on a particular site, because the event belongs to another site.
Details
* Stripe documents to only ever return a 2xx HTTP status code in a webhook endpoint: https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1136
* Stripe states that they do not evaluate the status code, as long as it is a 2xx code, although they do seem to make a differentiation between 4xx and 5xx codes - whereas 4xx means an error on the client-side (Stripe) and that the event can/should be tried again.  Therefore the …
=> Fixed Stripe disables webhook if multiple applications are connected to an account.

includes/class-wc-stripe-intent-controller.php
Fix for:
```php
PHP Notice:  Undefined property: stdClass::$error in [redacted]/wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-stripe-intent-controller.php on line 183
```
=> Add !empty check to avoid PHP notice

includes/class-wc-stripe-webhook-handler.php
Fixes https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1098
Fixes https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1306 (https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1232/commits/b627ac1e447655290cdf0093966927453604fd16)
See also https://github.com/woocommerce/woocommerce-gateway-stripe/issues/128 (h/t @jrick1229), partially addressed by https://github.com/woocommerce/woocommerce-gateway-stripe/commit/cb8d4bfc2e347b6f4a73f2ade5c3959e72eb92ea
Manipulates order status in response to `charge.dispute.closed` events. Draws on existing handling for reviews (original issue: https://github.com/woocommerce/woocommerce-gateway-stripe/issues/261), but restores earlier status when a dispute (or review) is resolved favorably.
When a dispute is closed …
=> Add handling for closed dispute webhook events

changelog.txt, includes/abstracts/abstract-wc-stripe-payment-gateway.php, includes/admin/stripe-settings.php, includes/class-wc-stripe-apple-pay-registration.php, includes/class-wc-stripe-webhook-handler.php, includes/class-wc-stripe-webhook-state.php, languages/woocommerce-gateway-stripe.pot, readme.txt, tests/phpunit/test-wc-stripe-webhook-state.php, woocommerce-gateway-stripe.php
Fixes #1200
Appends a message to the webhook settings description, with the date and time of the most recently received webhook event.
(Also tweaks the order of the settings, to group webhook-related items.)
Unit tests verify test and live mode messages. You can test manually using either test or live mode:
- Use stripe cli to send valid test webhooks: `stripe listen --forward-to "localhost:8082/?wc-api=wc_stripe"`.
- Paste your webhook secret in settings.
**Case 1: (Nominal case): Most recent webhook successful:**
- Run `stripe trigger payment_intent.created` to simulate a successful webhook and notice the following message:
> The most recent [mode] webhook, timestamped [timestamp], was processed successfully.
**Case 2: No webhook ever received (since this version of the plugin was …
=> Display time of last webhook in settings
