.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Added .github templates.

---

includes/settings-stripe.php

Props @jobthomas.
Resolves #14.

Provides better default title that consistent with other titles.

---

assets/js/stripe.js
includes/class-wc-gateway-stripe.php

When in order page make sure to check the order ID from query_vars.
Fixes #19.

Fixed issue where no param being passed to Stripe in pay order page.

---

woocommerce-gateway-stripe.php

Line #7 ```http://woothemes.com``` to ```httpS://woocommerce.com```

Add S & 'theme' to 'commerce'

---

includes/class-wc-gateway-stripe.php

Fixes https://github.com/woothemes/woocommerce-gateway-stripe/issues/30
@gedex #hackday

Add css class for specific targetting of an error

---

includes/class-wc-gateway-stripe.php

Show save to account for new accounts

---

changelog.txt
includes/class-wc-gateway-stripe.php

Fixes #51  .
- Add filter to the return value of generate_payment_request method.

New filter

---

includes/class-wc-gateway-stripe.php
includes/class-wc-stripe-customer.php
readme.txt

Fixes #135
* Add - Customer name and email to metadata.

Add metadata customer name and email fixes #135

---

includes/class-wc-stripe-payment-request.php

- Modify the total set in initial get_cart_details to include taxes.
- Add line items both in inital cart details and after a shipping option changes. The items are:
- Subtotal (excluding taxes)
- Shipping rate (if it's been selected by the user). Will use the name of the shipping method as defined by the store.
- Fees
- Taxes
Screenshot after the change

[Payment Request] Add and fix display line items.

---

readme.txt

Adds @deskroid to the list of authors.

---

readme.txt

adding @zandyring to contributors

add @zandyring to contributors

---

includes/class-wc-stripe-apple-pay.php
readme.txt
woocommerce-gateway-stripe.php

- Updates for WC 3.0 compatibility.

Updates for WC 3.0 compatibility.

---

includes/class-wc-gateway-stripe-addons.php

Fixes #229
cc @thenbrent - please see if this is what you're referring to? Thanks!

Add metadata URL for subs closes #229

---

includes/class-wc-stripe-api.php

Fixes # .
-send idempotency-key header

use headers with idempotency-key

---

tests/manual-tests.md

Initial work of manual tests instruction.
This branch is based off of `4.0.0` branch.
Preview: https://github.com/woocommerce/woocommerce-gateway-stripe/blob/558cb1938d670de895a4246a3b69bcac7d778f18/tests/manual-tests.md

[WIP] Manual tests instruction

---

includes/payment-methods/class-wc-stripe-payment-request.php

Fixes #466 
https://a8c.slack.com/archives/C0D9EC4H0/p1516291993000528
Give this a real test if you can, my test site / Stripe account isn't correctly set up to use payment requests buttons I think.

Set publishable key correctly based on test mode

---

includes/abstracts/abstract-wc-stripe-payment-gateway.php
includes/class-wc-gateway-stripe.php
includes/class-wc-stripe-api.php
includes/class-wc-stripe-order-handler.php
includes/compat/class-wc-stripe-compat.php
includes/compat/class-wc-stripe-sepa-compat.php
includes/payment-methods/class-wc-gateway-stripe-bitcoin.php
includes/payment-methods/class-wc-gateway-stripe-sepa.php
readme.txt

Fixes #522
* Fix - Potential issue when a charge parameter changes due to initial failed request causing retries to fail.

Idempotency

---

includes/class-wc-gateway-stripe.php

Hello, it's an improvement. This allows to display directly in the edition of an order the Stripes fees and also the net amount that will be credited the seller.

Display of Stripe fees as well as the net in one order.

---

includes/admin/stripe-eps-settings.php
includes/payment-methods/class-wc-gateway-stripe-eps.php
woocommerce-gateway-stripe.php

- add redirect flow based payment method EPS: https://stripe.com/docs/sources/eps
- this is pretty much equivalent to Giropay, but only supports banks in Austria

add EPS payment method

---

includes/admin/stripe-multibanco-settings.php

Typo fix in multibanco-settings

---

includes/class-wc-gateway-stripe.php

Cleaned up the text for easier reading.

Updated testing Stripe explanation

---

includes/class-wc-stripe-api.php

Fixes #655
* Added default emptystring for idempotency string
* if POST charges, store the value in the variable, and add to headers
* add idempotency key (emptystring, or filled) to log

Add default for idempotency key, and add it to logged failure

---

includes/class-wc-stripe-logger.php

BC change for creating a logger instance before 3.0.0

---

includes/admin/stripe-settings.php

Fixes #758.
- Enable saved cards by default.

Enable saved cards by default.

---

includes/class-wc-gateway-stripe.php

Fixes #814.
`prepare_source_from_intent` needed to borrow some logic from `WC_Gateway_Stripe::prepare_source` in order to work with tokes (saved payment methods). This PR includes those needed changes.

SCA: Save cards in checkout

---

includes/class-wc-stripe-helper.php

Check for empty charge id before taking action

---

.github/CONTRIBUTING.md
changelog.txt
readme.txt
woocommerce-gateway-stripe.php

- Update copy of readme
- woothemes > woocommerce GH org name
- Direct link to ticket form with extension selected
- Added new entry to changelog
no code changes

Small copy and tweaks

---

changelog.txt
tests/manual/manual-tests.md
tests/manual/stripe-alipay.md
tests/manual/stripe-bancontact.md
tests/manual/stripe-cc-elements.md
tests/manual/stripe-cc.md
tests/manual/stripe-checkout.md
tests/manual/stripe-giropay.md
tests/manual/stripe-ideal.md
tests/manual/stripe-p24.md
tests/manual/stripe-sepa.md
tests/manual/stripe-sofort.md
tests/manual/stripe-with-subscriptions.md

Fixes outdated manual tests
- updating the manual tests file with copy changes and other details
- mainly Checkout > Payments and other formatting

Manual tests update

---

includes/class-wc-stripe-intent-controller.php
includes/class-wc-stripe-webhook-handler.php

Fixes #858
In #849 we introduced a redirect after the checkout page for PI verification. During the review @DanReyLop [pointed out](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/849#discussion_r279691861) that `wp_die` is bad UX in case of errors.
- [Add logging for those errors](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/864/files#diff-456f6acd96f684a1fba901a950f7083fR127)
- Add redirects either to
- the "Order Received" page in case that an order could be loaded.
- the checkout page if the cart has not been emptied yet.
- the shop page if the cart is empty (nothing to display on the checkout page).
The latter two situations include a WooCommerce notice, while the "Order received" page would display the generic text, found in …

SCA: UX improvements for PaymentIntent verifications

---

.travis.yml
tests/bin/travis.sh

This PR fixes two Travis issues.
The error is:
> mysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to MySQL server on 'localhost' (111)'
This the same as the fix here: https://github.com/Automattic/woocommerce-payments/pull/145
The error:
> PHPUnit 7.5.0 by Sebastian Bergmann and contributors.
> This version of PHPUnit is supported on PHP 7.1 and PHP 7.2.
> You are using PHP 7.0.33 (/home/travis/.phpenv/versions/7.0.33/bin/php).
This is the same as the fix here: https://github.com/Automattic/woocommerce-payments/pull/150/files

Fix travis tests

---

tests/phpunit/test-wc-stripe-sub-renewal.php

Based on @RadoslavGeorgiev's change [here](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/963#discussion_r316327171), I realized we could actually test the statement descriptor 🎉
🙏 thanks Rado :)
The test works by adding the `woocommerce_stripe_settings` option to the test DB, and setting the payment method to stripe.
This could either be merged into `add/off-session-for-recurring-payments-938` before #955 is merged, or directly into `sca-subs/master` after #955 is merged.

Add statement descriptor test for renewal order

---

changelog.txt
languages/woocommerce-gateway-stripe.pot
package-lock.json
package.json
readme.txt
woocommerce-gateway-stripe.php

Note that this commit is out of order on `master`
and the 4.2.5 release was created using a separate branch.
It was branched off from edff7d6874e7b7f887dba38e2953d52f8b19da38
https://github.com/woocommerce/woocommerce-gateway-stripe/releases/tag/4.2.5

Update to version 4.2.5

---

changelog.txt
readme.txt

Add changelog entry for adding level3 data

---

.gitignore
composer.lock
package.json
tests/README.md

- Ignore VS Code configs
- Add readme for running PHP unit tests locally

Update local setup

---

changelog.txt
readme.txt

Update changelog prior to woorelease

---

woocommerce-gateway-stripe.php

Add WRCS comment to version define

---

readme.txt

Fix version in readme, update apple pay link

---

includes/class-wc-stripe-apple-pay-registration.php

Fixes https://github.com/woocommerce/woocommerce-gateway-stripe/issues/958
Fixes https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1298
Prevents error log and notice (and canceled domain verification process) in cases when domain association file cannot be written but is served manually.
If the file is already being served from the proper URL, don't log an error or show a notice. Otherwise, log an expanded message, e.g.:
```
2020-10-07T10:12:24+00:00 DEBUG 
====Stripe Version: 4.5.3====
====Start Log====
Error: Unable to copy domain association file to domain root. To enable Apple Pay, domain association file must be hosted at https://ephemeral-pauldechov-20201007.atomicsites.blog/.well-known/apple-developer-merchantid-domain-association.
====End Log====
```
(Can simulate …

Apple Pay: Only report domain association file copy error if not already present

---

SECURITY.md
changelog.txt
tasks/release.js

Fixes #1318 .
- Added SECURITY.md file

Added security.md file

---

readme.txt

Just an update to the readme to prepare for the 4.5.5 release.

Prepare to release version 4.5.5

---

changelog.txt
readme.txt

Add changelog entry for #1415 
N/A
(remove me)

Add changelog entry for PR#1415

---

changelog.txt
readme.txt

Adds a changelog for the upcoming 4.7.0 release.

Add changelog for 4.7.0 release

---

readme.txt

Description: Update reference to master branch in readme.txt.
Testing instructions: Make sure no reference to master branch in the codebase.

Update reference to master branch in readme.txt.
